@url = http://localhost:8080/api/preferences
###


GET {{url}}/2 HTTP/1.1

###


POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "preferencesId": 0,
    "userId": 2,
    "genres":["Action", "David", "Animation"],
    "platforms": ["Nintedo", "Logan", "PC", "XBOX"],
    "startDate": "2013-10-21",
    "endDate": "2023-10-07",
    "minMetaCritic": 10,
    "maxMetaCritic": 100
}

###

POST http://localhost:8080/api/user/authenticate HTTP/1.1
Content-Type: application/json

{
    "email": "kd@warriors.com",
    "passwd": "goDubs"
}

###